spring:
  profiles:
    include: oauth
  session:
    store-type: jdbc
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  h2:
    console:
      enabled: true
